CREATE VIEW [Tickets].[V_TicketFullDetails]
AS
SELECT
      t.[ticketID]
    , t.[ticketNo]
    , t.[idaraID_FK]
    , t.[parentTicketID_FK]
    , t.[rootTicketID_FK]
    , t.[serviceID_FK]
    , s.[serviceCode]
    , s.[serviceName_A]  AS [serviceName_A]
    , s.[serviceName_E]  AS [serviceName_E]
    , t.[ticketClassID_FK]
    , tc.[ticketClassCode]
    , tc.[ticketClassName_A]
    , tc.[ticketClassName_E]
    , t.[requesterTypeID_FK]
    , rt.[requesterTypeCode]
    , rt.[requesterTypeName_A]
    , rt.[requesterTypeName_E]
    , t.[requesterUserID_FK]
    , t.[requesterResidentID_FK]
    , t.[title]
    , t.[description_]
    , t.[suggestedPriorityID_FK]
    , t.[effectivePriorityID_FK]
    , p_e.[priorityCode]     AS [effectivePriorityCode]
    , p_e.[priorityName_A]   AS [effectivePriorityName_A]
    , p_e.[priorityName_E]   AS [effectivePriorityName_E]
    , t.[ticketStatusID_FK]
    , ts.[ticketStatusCode]
    , ts.[ticketStatusName_A]
    , ts.[ticketStatusName_E]
    , t.[currentDSDID_FK]
    , t.[currentQueueDistributorID_FK]
    , t.[assignedUserID_FK]
    , t.[locationBuildingNo]
    , t.[locationUnitNo]
    , t.[locationArea]
    , t.[operationalResolutionDate]
    , t.[finalClosureDate]
    , t.[requiresQualityReview]
    , t.[isOtherService]
    , t.[isParentBlocked]
    , t.[ticketActive]
    , t.[entryDate]          AS [ticketEntryDate]
    , t.[entryData]          AS [ticketEntryData]
    , t.[hostName]           AS [ticketHostName]
FROM [Tickets].[Ticket] t
LEFT JOIN [Tickets].[Service] s
    ON t.[serviceID_FK] = s.[serviceID]
LEFT JOIN [Tickets].[TicketClass] tc
    ON t.[ticketClassID_FK] = tc.[ticketClassID]
LEFT JOIN [Tickets].[RequesterType] rt
    ON t.[requesterTypeID_FK] = rt.[requesterTypeID]
LEFT JOIN [Tickets].[Priority] p_e
    ON t.[effectivePriorityID_FK] = p_e.[priorityID]
LEFT JOIN [Tickets].[TicketStatus] ts
    ON t.[ticketStatusID_FK] = ts.[ticketStatusID];
