-- ============================================================================
-- Table: Ticket
-- Schema: [Tickets]
-- Purpose: Stores the current state of ticket only (central transactional table)
-- Notes: One parent only. Root ticket reference is mandatory for tree-aware logic.
--          Requester can be resident OR internal user, not both at the same time.
--          IdaraID_FK is mandatory for filtering, reporting, dashboards.
-- ============================================================================

IF OBJECT_ID('[Tickets].[Ticket]', 'U') IS NOT NULL
    DROP TABLE [Tickets].[Ticket];
GO

CREATE TABLE [Tickets].[Ticket] (
    -- Primary Key
    [TicketID] BIGINT IDENTITY(1,1) NOT NULL,

    -- Unique Ticket Number (for external reference)
    [TicketNo] VARCHAR(20) NOT NULL,
    -- Format: TKT-YYYY-XXXXXX (generated by SP)

    -- IdaraID_FK is mandatory for filtering and reporting
    [IdaraID_FK] INT NOT NULL,

    -- Parent-Child Ticket Fields (for dependency tracking)
    [ParentTicketID_FK] BIGINT NULL, -- One parent only
    [RootTicketID_FK] BIGINT NULL, -- Required for tree reporting and cross-level aggregation

    -- Service Information
    [ServiceID_FK] BIGINT NULL, -- NULL for "Other" service type
    [IsOtherService] BIT NOT NULL CONSTRAINT DF_Ticket_IsOtherService DEFAULT 0,

    -- Ticket Classification
    [TicketClassID_FK] INT NOT NULL, -- Reference to [Tickets].[TicketClass]

    -- Requester Information
    [RequesterTypeID_FK] INT NOT NULL, -- Reference to [Tickets].[RequesterType]
    [RequesterUserID_FK] BIGINT NULL, -- Reference to existing User table (internal)
    [RequesterResidentID_FK] BIGINT NULL, -- Reference to resident table (external)
    [RequesterName] VARCHAR(200) NULL, -- Display name for external requesters
    [RequesterContact] VARCHAR(100) NULL, -- Contact info for external requesters

    -- Ticket Details
    [Title] VARCHAR(200) NOT NULL,
    [TitleAR] NVARCHAR(200) NULL, -- Arabic title for bilingual support
    [Description] VARCHAR(MAX) NULL,
    [DescriptionAR] NVARCHAR(MAX) NULL,
    [Location] VARCHAR(255) NULL,
    [LocationDetails] VARCHAR(500) NULL,

    -- Priority Management
    [SuggestedPriorityID_FK] INT NULL, -- Priority requested by user
    [EffectivePriorityID_FK] INT NOT NULL, -- Actual priority assigned (from service default or override)

    -- Status Management
    [TicketStatusID_FK] INT NOT NULL, -- Reference to [Tickets].[TicketStatus]
    [SubStatus] VARCHAR(50) NULL, -- Additional status context

    -- Routing Information (Queue routing is different from execution assignment)
    [CurrentDSDID_FK] BIGINT NOT NULL, -- Current organizational queue (reference to DSDID)
    [CurrentQueueDistributorID_FK] BIGINT NULL, -- Reference to existing Distributor table
    [AssignedUserID_FK] BIGINT NULL, -- Assigned to real user (execution assignment)
    [AssignedAt] DATETIME2 NULL,
    [AcceptedAt] DATETIME2 NULL,

    -- Work Execution
    [InProgressAt] DATETIME2 NULL,
    [OperationalResolvedAt] DATETIME2 NULL,
    [OperationalResolvedBy] BIGINT NULL,
    [FinallyClosedAt] DATETIME2 NULL,
    [FinallyClosedBy] BIGINT NULL,

    -- Quality Review Configuration
    [RequiresQualityReview] BIT NOT NULL CONSTRAINT DF_Ticket_RequiresQualityReview DEFAULT 1,
    [QualityReviewerID_FK] BIGINT NULL,

    -- Parent Blocking State
    [IsParentBlocked] BIT NOT NULL CONSTRAINT DF_Ticket_IsParentBlocked DEFAULT 0,
    [BlockedSince] DATETIME2 NULL,

    -- SLA Reference (computed/stored separately)
    [LastSLACalculatedAt] DATETIME2 NULL,

    -- Additional Metadata
    [Tags] VARCHAR(500) NULL,
    [CustomField1] VARCHAR(255) NULL,
    [CustomField2] VARCHAR(255) NULL,

    -- Audit Columns
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Ticket_CreatedAt DEFAULT SYSDATETIME(),
    [UpdatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Ticket_UpdatedAt DEFAULT SYSDATETIME(),
    [CreatedBy] VARCHAR(100) NULL,
    [UpdatedBy] VARCHAR(100) NULL,

    -- Primary Key Constraint
    CONSTRAINT PK_Ticket PRIMARY KEY CLUSTERED ([TicketID])
);
GO

-- Foreign Key Constraints
ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_Service
    FOREIGN KEY ([ServiceID_FK]) REFERENCES [Tickets].[Service]([ServiceID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_TicketClass
    FOREIGN KEY ([TicketClassID_FK]) REFERENCES [Tickets].[TicketClass]([TicketClassID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_RequesterType
    FOREIGN KEY ([RequesterTypeID_FK]) REFERENCES [Tickets].[RequesterType]([RequesterTypeID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_SuggestedPriority
    FOREIGN KEY ([SuggestedPriorityID_FK]) REFERENCES [Tickets].[Priority]([PriorityID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_EffectivePriority
    FOREIGN KEY ([EffectivePriorityID_FK]) REFERENCES [Tickets].[Priority]([PriorityID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_TicketStatus
    FOREIGN KEY ([TicketStatusID_FK]) REFERENCES [Tickets].[TicketStatus]([TicketStatusID]);

-- Self-reference for parent-child relationship
ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_Parent
    FOREIGN KEY ([ParentTicketID_FK]) REFERENCES [Tickets].[Ticket]([TicketID]);

ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT FK_Ticket_Root
    FOREIGN KEY ([RootTicketID_FK]) REFERENCES [Tickets].[Ticket]([TicketID]);
GO

-- Unique Constraint: Ticket No must be unique
ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT UQ_Ticket_TicketNo UNIQUE ([TicketNo]);
GO

-- Indexes
CREATE UNIQUE NONCLUSTERED INDEX IX_Ticket_TicketNo
ON [Tickets].[Ticket] ([TicketNo]);

CREATE NONCLUSTERED INDEX IX_Ticket_ServiceID
ON [Tickets].[Ticket] ([ServiceID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_CurrentDSDID
ON [Tickets].[Ticket] ([CurrentDSDID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_AssignedUserID
ON [Tickets].[Ticket] ([AssignedUserID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_TicketStatusID
ON [Tickets].[Ticket] ([TicketStatusID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_ParentTicketID
ON [Tickets].[Ticket] ([ParentTicketID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_RootTicketID
ON [Tickets].[Ticket] ([RootTicketID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_RequesterUserID
ON [Tickets].[Ticket] ([RequesterUserID_FK]);

CREATE NONCLUSTERED INDEX IX_Ticket_CreatedAt
ON [Tickets].[Ticket] ([CreatedAt] DESC);

CREATE NONCLUSTERED INDEX IX_Ticket_EffectivePriorityID_CreatedAt
ON [Tickets].[Ticket] ([EffectivePriorityID_FK], [CreatedAt] DESC);

-- Composite index for inbox queries (by status + DSDID + created date)
CREATE NONCLUSTERED INDEX IX_Ticket_InboxQuery
ON [Tickets].[Ticket] ([TicketStatusID_FK], [CurrentDSDID_FK], [CreatedAt] DESC)
INCLUDE ([TicketNo], [Title], [EffectivePriorityID_FK], [AssignedUserID_FK]);
GO

-- Check Constraint: Requester cannot be both resident and internal user
ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT CK_Ticket_RequesterType
    CHECK (
        (RequesterTypeID_FK IN (SELECT RequesterTypeID FROM [Tickets].[RequesterType] WHERE IsInternal = 1) AND RequesterUserID_FK IS NOT NULL AND RequesterResidentID_FK IS NULL) OR
        (RequesterTypeID_FK IN (SELECT RequesterTypeID FROM [Tickets].[RequesterType] WHERE IsInternal = 0) AND RequesterResidentID_FK IS NOT NULL AND RequesterUserID_FK IS NULL)
    );

-- Simplified Check: One of RequesterUserID_FK or RequesterResidentID_FK must be NULL
ALTER TABLE [Tickets].[Ticket]
ADD CONSTRAINT CK_Ticket_SingleRequester
    CHECK ((RequesterUserID_FK IS NULL) OR (RequesterResidentID_FK IS NULL));
GO

-- Comment: This is the central transactional table of the ticketing system.
-- CurrentDSDID_FK is the source of truth for routing.
-- Queue routing (via CurrentQueueDistributorID_FK) is separate from execution assignment (via AssignedUserID_FK).
-- RootTicketID_FK is required for all tree-aware queries and reporting.
-- Parent-child relationships enable dependency tracking between tickets.
-- IsParentBlocked flag indicates if this ticket is waiting for a child ticket to complete.
