CREATE TABLE [Tickets].[Ticket] (
    [ticketID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ticketNo]                      NVARCHAR (50)   NOT NULL,
    [idaraID_FK]                    INT             NOT NULL,
    [parentTicketID_FK]             BIGINT          NULL,
    [rootTicketID_FK]               BIGINT          NULL,
    [serviceID_FK]                  BIGINT          NULL,
    [ticketClassID_FK]              INT             NOT NULL,
    [requesterTypeID_FK]            INT             NOT NULL,
    [requesterUserID_FK]            INT             NULL,
    [requesterResidentID_FK]        BIGINT          NULL,
    [title]                         NVARCHAR (500)  NOT NULL,
    [description_]                  NVARCHAR (4000) NULL,
    [suggestedPriorityID_FK]        INT             NULL,
    [effectivePriorityID_FK]        INT             NULL,
    [ticketStatusID_FK]             INT             NOT NULL,
    [currentDSDID_FK]               INT             NULL,
    [currentQueueDistributorID_FK]  INT             NULL,
    [assignedUserID_FK]             INT             NULL,
    [locationBuildingNo]            NVARCHAR (100)  NULL,
    [locationUnitNo]                NVARCHAR (50)   NULL,
    [locationArea]                  NVARCHAR (200)  NULL,
    [operationalResolutionDate]     DATETIME        NULL,
    [finalClosureDate]              DATETIME        NULL,
    [requiresQualityReview]         BIT             NULL,
    [isOtherService]                BIT             NULL,
    [isParentBlocked]               BIT             NULL,
    [ticketActive]                  BIT             NULL,
    [entryDate]                     DATETIME        CONSTRAINT [DF_Tickets_Ticket_entryDate] DEFAULT (GETDATE()) NULL,
    [entryData]                     NVARCHAR (20)   NULL,
    [hostName]                      NVARCHAR (200)  NULL,
    CONSTRAINT [PK_Tickets_Ticket] PRIMARY KEY CLUSTERED ([ticketID] ASC)
);
